### ISSUE TITLE
Throw Pokeball.js

### ISSUE THREAD

**Issue by 0xKryn** [abstraction/delugerpg-bots#1]
Not throwing any pokeball juat selecting sir

**Comment by himanshuksr0007** [comment]
I am facing the same issue and it had to do something with the error [attached in the image] tried multiple things to resolve this but to no avail 

![Screenshot_2024-04-14-18-47-58-46_4d38fce200f96aeac5e860e739312e76](https://github.com/abstraction/delugerpg-bots/assets/83110103/f4aebab5-049f-446c-8479-0b642c6f74f6)

**Comment by abstraction** [comment]
Fixed. Also, make sure you install the following scripts for pokemon catcher from the [pokemon-catcher](https://github.com/abstraction/delugerpg-bots/tree/master/src/pokemon-catcher) folder:

- [pokemon-catcher.user.js](https://github.com/abstraction/delugerpg-bots/blob/master/src/pokemon-catcher/pokemon-catcher.user.js) (you can select which class to catch from [here](https://github.com/abstraction/delugerpg-bots/blob/a80466d697bf445c7b6404e05c3982fd0da3b431/src/pokemon-catcher/pokemon-catcher.user.js#L269) by simply commenting/uncommenting, currently catches retro, shiny and chrome)
- [throw-pokeballs.user.js](https://github.com/abstraction/delugerpg-bots/blob/master/src/pokemon-catcher/throw-pokeballs.user.js) (essential)
- [walk-more.user.js](https://github.com/abstraction/delugerpg-bots/blob/master/src/pokemon-catcher/walk-more.user.js) (essential)
- [catching-captcha.user.js](https://github.com/abstraction/delugerpg-bots/blob/master/src/pokemon-catcher/catching-captcha.user.js) (optional to stay logged in)

I don't play the game anymore, so feel free to let me know if anything breaks :)
